### ISSUE TITLE
Installing `mysql-libs=8.0.27=hfa10184_2` broke some environment

### ISSUE THREAD

**Issue by beenje** [conda-forge/mysql-feedstock#60]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Installing `mysql-libs=8.0.27=hfa10184_2` broke some of my environment that worked fine with `mysql-libs=8.0.27=hfa10184_1`. I get the following error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: /opt/conda/envs/icepap/lib/python3.10/site-packages/PyQt5/../../../libstdc++.so.6: cannot allocate memory in static TLS block
```

Running `python -c "import MySQLdb"` works. So maybe an incompatibility between this new build and PyQt5 or another package?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda/envs/icepap:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifultable            1.0.1              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
click                     8.0.3                    pypi_0    pypi
configobj                 5.0.6                      py_0    conda-forge
dbus                      1.13.6               h48d8840_2    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
glib                      2.70.2               h780b84a_0    conda-forge
glib-tools                2.70.2               h780b84a_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_2    conda-forge
gstreamer                 1.18.5               h9f60fe5_2    conda-forge
icepap                    3.6.3              pyhd8ed1ab_0    conda-forge
icepapcms                 3.3.1              pyhd8ed1ab_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
ipy                       1.01               pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
ldap3                     2.9.1              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.2               h174f98d_0    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mysql-common              8.0.27               ha770c72_2    conda-forge
mysql-libs                8.0.27               hfa10184_2    conda-forge
mysqlclient               2.0.3                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.73                 hb5efdd6_0    conda-forge
numpy                     1.21.4                   pypi_0    pypi
openssl                   1.1.1l               h7f98852_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
prompt_toolkit            3.0.24               hd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt-impl                 5.12.3          py310h1f8e252_8    conda-forge
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.10.0          h62f1059_3_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyyaml                    6.0                      pypi_0    pypi
qt                        5.12.9               hda022c4_4    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                59.6.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
storm                     0.25                     pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : icepap
    active env location : /opt/conda/envs/icepap
            shell level : 2
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __linux=5.10.47=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.10.47-linuxkit centos/7.9.2009 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

How to reproduce:

```
$ mamba create -y -n icepap icepapcms mysqlclient
$ conda activate icepap
$ icepapcms --help
Traceback (most recent call last):
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: /opt/conda/envs/icepap/lib/python3.10/site-packages/PyQt5/../../../libstdc++.so.6: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/icepap/bin/icepapcms", line 6, in <module>
    from icepapcms.__main__ import main
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/icepapcms/__main__.py", line 6, in <module>
    from .lib import ConfigManager
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/icepapcms/lib/__init__.py", line 1, in <module>
    from .mainmanager import *
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/icepapcms/lib/mainmanager.py", line 19, in <module>
    from .stormmanager import StormManager
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/icepapcms/lib/stormmanager.py", line 21, in <module>
    from .stormmysql import MySQL
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/icepapcms/lib/stormmysql.py", line 30, in <module>
    import MySQLdb
  File "/opt/conda/envs/icepap/lib/python3.10/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined

# Forcing the previous build fixes the issue
$ mamba install mysql-libs=8.0.27=hfa10184_1
$ icepapcms --help
usage: Icepap Configuration Manager System (CMS) [-h] [-e] [-s] [--all-networks] [-c CONFIG_FILE] [-u] [--debug-level DEBUG_LEVEL]
```

**Comment by beenje** [comment]
While googling this error I found this issue https://bugs.launchpad.net/ubuntu/+source/opencv/+bug/1890170

I confirm the new build has the `STATIC_TLS` flag
```
(icepap) [root@f4e73dee4077 pkgs]# readelf --dynamic /opt/conda/pkgs/mysql-libs-8.0.27-hfa10184_1/lib/libmysqlclient.so | grep BIND
 0x0000000000000018 (BIND_NOW)
(icepap) [root@f4e73dee4077 pkgs]# readelf --dynamic /opt/conda/pkgs/mysql-libs-8.0.27-hfa10184_2/lib/libmysqlclient.so | grep BIND
 0x000000000000001e (FLAGS)              BIND_NOW STATIC_TLS
```

**Comment by nehaljwani** [comment]
This is fixed:

```
❯❯❯ readelf --dynamic  ~/m3/pkgs/mysql-libs-8.0.27-hfa10184_3/lib/libmysqlclient.so | grep BIND
 0x0000000000000018 (BIND_NOW)
```

Thank you for reporting!

**Comment by beenje** [comment]
Thanks!
